apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphabeta
spec:
  selector:
    matchLabels:
      app: alphabeta
  template:
    metadata:
      labels:
        app: alphabeta
    spec:
      containers:
      - name: alphabeta
        image: ghcr.io/bmxguy100/alphabeta
        resources: {}
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alphabeta
spec:
  selector:
    app: alphabeta
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alphabeta
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: alphabeta.appjackstudio.com
    http:
      paths:
      - backend:
          service:
            name: alphabeta
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - alphabeta.appjackstudio.com
    secretName: alphabeta-tls
